feat: add GitHub Actions for hotfix and release workflows, including version bumping and publishing to NPM
ArkaneNetwork/web3-react-venly pull request #14
Opened 2024-08-30 09:00 UTC by koen-venly

2024-09-10 10:21 UTC, nico-ptrs requested changes
I'm not really sure if the actions should be in this project. Shouldn't they be in [venly-github-workflows](https://github.com/ArkaneNetwork/venly-github-workflows)?

2024-09-11 05:23 UTC, koen-venly commented
@nico-ptrs Yes, but for public projects, actions can't be used from our venly-github-workflows.

2024-09-11 05:24 UTC, koen-venly commented
@nico-ptrs Yes, but for public projects, actions can't be used from our venly-github-workflows.

2024-10-07 13:54 UTC, nico-ptrs approved these changes

2024-10-07 14:26 UTC, merged